apiVersion: apps/v1
kind: Deployment
metadata:
  name: avihay-wordle-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordle
  template:
    metadata:
      labels:
        app: wordle
    spec:
      containers:
      - name: avihay-wordle
        image: avihays/wordle:latest
        ports:
        - containerPort: 8080  
